(function (root, exports) {
  if (typeof define === "function" && define.amd) {
    // AMD. Register as an anonymous module.
    define([], function () {
      return exports;
    });
  } else if (typeof module === "object" && module.exports) {
    // Node. Does not work with strict CommonJS, but
    // only CommonJS-like environments that support module.exports,
    // like Node.
    module.exports = exports;
  } else {
    // Browser globals (root is window)
    root.hyphenationPatternsId = exports;
  }
})(this, [
  [
    [0, 1],
    [2, 1],
    [2, 0, 1],
    [2, 3, 2],
    [0, 0, 2, 3],
    [0, 0, 2, 0, 3],
    [2],
    [0, 2, 1],
    [0, 2],
    [1, 0, 1, 0, 2],
    [3],
    [0, 2, 0, 2],
    [0, 0, 3, 0, 4]
  ],
  {
    a: [{ i: { r: 8 }, n: { ".": 10 } }, 0],
    e: 0,
    i: [{ o: { n: 7 } }, 0],
    o: 0,
    u: 0,
    b: {
      d: 1,
      j: 1,
      k: 1,
      n: 1,
      s: 1,
      t: 1,
      a: { g: { a: { i: 9 } }, n: { ".": 1 } }
    },
    c: { k: 1, n: 1, a: { n: { ".": 1 } } },
    d: { k: 1, n: 1, p: 1, a: { n: { ".": 1 } } },
    f: { d: 1, k: 1, n: 1, t: 1, a: { n: { ".": 1 } } },
    g: { g: 1, k: 1, n: 1, a: { n: { ".": 1 } } },
    h: { k: 1, l: 1, m: 1, n: 1, w: 1, a: { n: { ".": 1 } } },
    j: { k: 1, n: 1, a: { n: { ".": 1 } } },
    k: { b: 1, k: 1, m: 1, n: 1, r: 1, s: 1, t: 1, a: { n: { ".": 1 } } },
    l: {
      b: 1,
      f: 1,
      g: 1,
      h: 1,
      k: 1,
      m: 1,
      n: 1,
      s: 1,
      t: 1,
      q: 1,
      a: { n: { ".": 1 } }
    },
    m: { b: 1, k: 1, l: 1, m: 1, n: 1, p: 1, r: 1, s: 1, a: { n: { ".": 1 } } },
    n: {
      c: 1,
      d: 1,
      f: 1,
      j: 1,
      k: 1,
      n: 1,
      p: 1,
      s: [{ t: 3 }, 1],
      t: 1,
      v: 1,
      g: { g: 2, h: 2, k: 2, n: 2, s: 2, ".": 6, a: { n: { ".": 2 } } },
      y: { ".": 6 },
      a: { n: { ".": 1 } }
    },
    p: { k: 1, n: 1, p: 1, r: 1, t: 1, a: { n: { ".": 1 } } },
    r: {
      b: 1,
      c: 1,
      f: 1,
      g: 1,
      h: 1,
      j: 1,
      k: 1,
      l: 1,
      m: 1,
      n: 1,
      p: 1,
      r: 1,
      s: 1,
      t: 1,
      w: 1,
      y: 1,
      a: { n: { ".": 1 } }
    },
    s: {
      b: 1,
      k: 1,
      l: 1,
      m: 1,
      n: 1,
      p: 1,
      r: 1,
      s: 1,
      t: 1,
      w: 1,
      a: { n: { ".": 1 } }
    },
    t: { k: 1, l: 1, n: 1, t: 1, a: { n: { ".": 1 } } },
    w: { t: 1 },
    ".": {
      b: { e: { r: 4 } },
      t: { e: { r: 4 }, a: { n: { g: { a: { n: { ".": 12 } } } } } },
      m: { e: { n: { g: 5 } }, a: { n: { g: { a: { n: { ".": 12 } } } } } },
      p: { e: { r: 4 }, a: { n: { g: { a: { n: { ".": 12 } } } } } },
      a: { t: { a: { u: 11 } } },
      l: { e: { n: { g: { a: { n: { ".": 12 } } } } } },
      j: { a: { n: { g: { a: { n: { ".": 12 } } } } } },
      r: { i: { n: { g: { a: { n: { ".": 12 } } } } } },
      d: { e: { n: { g: { a: { n: { ".": 12 } } } } } }
    },
    v: { a: { n: { ".": 1 } } },
    z: { a: { n: { ".": 1 } } }
  },
  {
    berabe: [2, 5],
    berahi: [2, 5],
    berak: [2],
    beranda: [2, 6],
    berandal: [2, 6],
    berang: [2],
    berangasan: [2, 5, 10],
    berangsang: [2, 7],
    berangus: [2, 5],
    berani: [2, 5],
    berantakan: [2, 6, 10],
    berantam: [2, 6],
    berantas: [2, 6],
    berapa: [2, 5],
    beras: [2],
    berendeng: [2, 6],
    berengut: [2, 5],
    bererot: [2, 5],
    beres: [2],
    berewok: [2, 5],
    beri: [2],
    beringas: [2, 5],
    berisik: [2, 5],
    berita: [2, 5],
    berok: [2],
    berondong: [2, 6],
    berontak: [2, 6],
    berudu: [2, 5],
    beruk: [2],
    beruntun: [2, 6],
    pengekspor: [4, 8],
    pengimpor: [4, 7],
    tera: [2],
    terang: [2],
    teras: [2],
    terasi: [2, 5],
    teratai: [2, 5],
    terawang: [2, 5],
    teraweh: [2, 5],
    teriak: [2, 5],
    terigu: [2, 5],
    terik: [2],
    terima: [2, 5],
    teripang: [2, 5],
    terobos: [2, 5],
    terobosan: [2, 5, 9],
    teromol: [2, 5],
    terompah: [2, 6],
    terompet: [2, 6],
    teropong: [2, 5],
    terowongan: [2, 5, 10],
    terubuk: [2, 5],
    teruna: [2, 5],
    terus: [2],
    terusi: [2, 5]
  }
]);
